config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index', as: :tasks
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(set_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(set_params)
    redirect_to task_path(@task)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

  private

  def set_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_area :title %>
  <%= f.label :details %>
  <%= f.text_area :details %>
  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed, :class => "chckbx_form"%>
  </div>
  <%= f.submit :class => "submit"%>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>

  <%= render 'form', task: @task %>

  <hr>

  <img id="back" src="https://image.flaticon.com/icons/png/512/0/340.png">
  <%= link_to "Back to tasks list", tasks_path, {:class=>"back_tasks"} %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>

  <div class="tasks">
    <% @tasks.each do |task| %>
      <% if task.completed == false %>
      <div class="task_info">
        <input type="checkbox" disabled="disabled">
        <p><%= link_to task.title, task_path(task) %>
          <%= link_to image_tag("https://cdn3.iconfinder.com/data/icons/cleaning-icons/512/Trash_Can-512.png"), delete_path(task), method: :delete %></p>
      </div>
      <% else %>
      <div class="task_info">
        <input type="checkbox" checked disabled="disabled">
        <p><%= link_to task.title, task_path(task) %> <%= link_to image_tag("https://cdn3.iconfinder.com/data/icons/cleaning-icons/512/Trash_Can-512.png"), delete_path(task), method: :delete %></p>
      </div>
    <% end %>
    <% end %>
  </div>

  <hr>

  <%= link_to "Create new task", new_task_path, {:class=>"new_btn"} %>
</div>

<img src="" alt="">

app/views/tasks/new.html.erb
<div class="container">
  <h1>New Task</h1>

  <%= render 'form', task: @task %>

  <hr>
  <img id="back" src="https://image.flaticon.com/icons/png/512/0/340.png">
  <%= link_to "Back to tasks list", tasks_path, {:class=>"back_tasks"} %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1>Task</h1>
  <div id="edit_task_btn">
    <%= link_to "Edit this task", edit_task_path, {:class=>"edit_btn"} %>
  </div>

  <p style="background-color: lightgrey; padding: 20px;" id="task_details"><%= @task.details %></p>

  <% if @task.completed == false %>
    <div class="task_info">
      <input type="checkbox" disabled="disabled">
      <p><%= "This task is not completed yet" %></p>
    </div>
    <% else %>
    <div class="task_info">
      <input type="checkbox" checked disabled="disabled">
      <p><%= "This task is completed" %></p>
    </div>
  <% end %>

  <hr>

  <img id="back" src="https://image.flaticon.com/icons/png/512/0/340.png">
  <%= link_to "Back to tasks list", tasks_path, {:class=>"back_tasks"} %>
</div>